sudo: required
services:
  - docker

before_install:
  - docker build -t dinesh/docker-react -f Dockerfile.dev .

script:
  - docker run -p 3000:3000 dinesh/docker-react  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-491357278298"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"